name: Scrape and Notify

on:
  schedule:
  - cron: '0 12 * * 1-5'  # 平日のみ21時（JST）に実行（12:00 UTC）
  workflow_dispatch:    # 手動実行も可能

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium and chromedriver
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser chromium-chromedriver
            pip install -r scraper/requirements.txt

      - name: Run scraper
        run: python scraper/scraper.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
